from django.contrib import admin
from .models import Food, Brand, Category


@admin.register(Food)
class FoodAdmin(admin.ModelAdmin):
    list_display = ("name",
                    "brand",
                    "category",
                    "energy",
                    "protein",
                    "fat",
                    "carbohydrate",
                    "sugar",
                    "sodium",
                    "cholesterol",
                    "saturate_fat",
                    "trans_fat",
                    "hydrate",
                    "saccharose",
                    "glucose",
                    "fructose",
                    "lactose",
                    "maltose",
                    "dietary_fiber",
                    "calcium",
                    "iron",
                    "magnesium",
                    "phosphorus",
                    "kalium",
                    "zinc",
                    "copper",
                    "manganese",
                    "selenium",
                    "beta_carotene",
                    "vitamin_d3",
                    "tocopherol",
                    "tocotrienols",
                    "vitamin_b1",
                    "vitamin_b2",
                    "niacin",
                    "folate",
                    "vitamin_b12",
                    "vitamin_c",
                    "amino_acid",
                    "isoleucine",
                    "leucine",
                    "lysine",
                    "methionine",
                    "phenylalanine",
                    "threonine",
                    "valine",
                    "histidine",
                    "arginine",
                    "tyrosine",
                    "cysteine",
                    "alanine",
                    "aspartic_acid",
                    "glutamic_acid",
                    "glycine",
                    "proline",
                    "serine",
                    "butyric_acid",
                    "caproic_acid",
                    "caprylic_acid",
                    "capric_acid",
                    "lauric_acid",
                    "myristic_acid",
                    "palmitic_acid",
                    "stearic_acid",
                    "arachidic_acid",
                    "myristoleic_acid",
                    "palmitoleic_acid",
                    "oleic_acid",
                    "vaccenic_acid",
                    "gadoleic_acid",
                    "linoleic_acid",
                    "alpha_linolenic_acid",
                    "gamma_linolenic_acid",
                    "eicosadienoic_acid",
                    "arachidonic_acid",
                    "eicosatrienoic_acid",
                    "eicosapentaenoic_acid",
                    "docosapentaenoic_acid",
                    "docosahexaenoic_acid",
                    "trans_oleic_acid",
                    "trans_linoleic_acid",
                    "trans_linolenic_acid",
                    "ash",
                    "caffeine",
                    "retinol",
                    "sugar_alcohol",
                    "erythritol",
                    "iodine",
                    "chloride",
                    "vitamin_d",
                    "vitamin_d1",
                    "vitamin_e",
                    "vitamin_k",
                    "vitamin_k1",
                    "vitamin_k2",
                    "pantothenic_acid",
                    "vitamin_b6",
                    "biotin",
                    "choline",
                    "tryptophan",
                    "taurine",
                    "omega_3_fatty_acids",
                    "total_unsaturated_fats",
                    )


@admin.register(Brand)
class BrandAdmin(admin.ModelAdmin):
    list_display = ("name",)


@admin.register(Category)
class CategoryAdmin(admin.ModelAdmin):
    list_display = ("name",)

